env:
    browser: true
    es6: true
    node: true
    jest: true
extends:
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 2018
    sourceType: module
    project: './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - 'jest'
rules:
    '@typescript-eslint/no-unused-vars-experimental': error
    '@typescript-eslint/ban-ts-ignore': off
